<!doctype html>
<html lang="en" class="fullscreen-bg">

<head>
    <title>登录</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="/layui/css/layui.css">

    <link rel="stylesheet" href="../assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="../assets/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="../assets/vendor/linearicons/style.css">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="../assets/css/main.css">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="../assets/css/demo.css">
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <!-- ICONS -->
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" sizes="96x96" href="../assets/img/favicon.png">
    <script src="/assets/vendor/jquery/jquery.min.js"></script>

    <!--  layer css  -->
    <!--  layer js  -->
    <script src="/layui/layui.js"></script>

    <!--  common js  -->
    <script src="/assets/js/common.js"></script>
</head>

<body>
<!-- WRAPPER -->
<div id="wrapper">
    <div class="vertical-align-wrap">
        <div class="vertical-align-middle">
            <div class="auth-box ">
                <div class="left">
                    <div class="content">
                        <div class="header">
                            <div class="logo text-center"><img src="../assets/img/logo-dark.png" alt="Klorofil Logo"></div>
                        </div>
                        <div class="form-auth-small" action="/login/in" method="post">
                            <div class="form-group">
                                <label for="signin-email" class="control-label sr-only">用户</label>
                                <input type="text" class="form-control" id="input-username" value="" placeholder="输入用户名">
                            </div>
                            <div class="form-group">
                                <label for="signin-password" class="control-label sr-only">TOTP</label>
                                <input type="text" class="form-control" id="input-totp" value="" placeholder="输入六位TOTP码">
                            </div>
                            <button type="submit" class="btn btn-primary btn-lg btn-block" onclick="onLogin()">登录</button>
                        </div>
                    </div>
                </div>
                <div class="right">
                    <div class="overlay"></div>
                    <div class="content text">
                        <h1 class="heading" style="font-weight: bold">下载：Google Authenticator</h1>
                        <h3 >
                            <a style="color:;" href="https://help.aliyun.com/document_detail/28668.html" target="_blank">IOS下载地址</a>
                        </h3>
                        <h3>
                            <a href="https://helpcdn.aliyun.com/document_detail/28669.html" target="_blank">安卓下载地址</a>
                        </h3>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
<script src="/assets/js/login.js"></script>
<!-- END WRAPPER -->
</body>

</html>
