<!-- MAIN CONTENT -->
<div class="main-content">
    <div class="container-fluid">
        <h3 class="page-title">
            <div class="text-left col-md-6"><?=$user['username']?> <?=$user['comment'] ? $user['comment'] : ''?>
                - 可见项目列表 (总数<?=count($projects)?>)</div>
            <div class="text-right col-md-6">
                <a href="/project/create">
                    <button type="button" class="btn btn-primary">项目申请</button>
                </a>
            </div>
        </h3>
        <hr>
        <div class="row">
            <div class="col-md-12">
                <!-- TABLE HOVER -->
                <div class="panel">
                    <div class="panel-body">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>项目名称</th>
                                <th>域名</th>
                                <th>二级目录</th>
                                <th>环境</th>
                                <th>节点</th>
                                <th>上线次数</th>
                                <th>最近上线时间</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            foreach ($projects as $v) :?>
                                <tr>
                                    <td><?= $v['id'] ?></td>
                                    <td><?= $v['project_name'] ?></td>
                                    <td><?= $v['domain'] ?></td>
                                    <td><?= $v['domain_second_path'] ?></td>
                                    <td><?= $v['env_name'] ?></td>
                                    <td><?= $v['batch_size'] ?></td>
                                    <td><?= $v['online_num'] ?></td>
                                    <td><?= $v['use_time'] ?></td>
                                    <td>
                                        <a target="_blank" href="/project/detail?id=<?= $v['id'] ?>">
                                            <button type="button" class="btn btn-sm btn-primary">详情</button>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- END TABLE HOVER -->
            </div>
        </div>
    </div>
</div>
